#########################
# setting up working environment 
#########################

rm(list=ls()) # delete all objects in the workspace
gc(reset=T) # resest memory (especially useful when working with large data sets)

options(stringsAsFactors=F) # disables automatic conversion of char. strings into factors

BASE="initial/directory/you/are/operating/in/on/your/local/machine/"

#########################
# setting up working environment 
#########################

library(tidyverse)
library(ggplot2)
library(data.table)
library(ggtree)
library(gridExtra)
library(grid)
library(ape)

#########################


# load file generated by https://genevo.pasteur.fr/, enter the OT pathway gene set as gene list
# gene list used: 
# OT_list = c('GUCY1A2', 'GUCY1A1', 'CACNA2D2', 'CACNA2D1', 'CACNA2D4',  'CACNA2D3','PRKAB1', 'PRKAB2', 'PPP1CA', 'PPP1CB',
# 'MYL6', 'MYL9', 'CALM2','CALM3','RAF1', 'CALM1','PRKAA2', 'ROCK1','ADCY1','ROCK2',
# 'CALML6', 'ADCY5', 'CALML3', 'ADCY4','CALML4', 'ADCY3','ADCY2','CALML5', 'ADCY9','EGFR',   
# 'PRKAA1', 'ADCY8','ADCY7','ADCY6','PPP1CC', 'NRAS', 'ACTB',  'CCND1', 'MAP2K5', 'PRKCG',
# 'MAP2K2', 'PLA2G4E','PLA2G4F','MAP2K1', 'PLA2G4C','PLA2G4D','PLA2G4A','PLA2G4B','PRKCB','EEF2',
# 'PRKCA',  'CACNB2', 'RCAN1',  'CACNB3', 'CACNB4', 'GNAQ', 'GNAS','CACNB1','OXTR', 'GUCY1B1',
# 'CACNA1C','ACTG1','CACNA1D','ELK1',  'CACNA1F', 'MYL6B','MYLK', 'TRPM2','PPP3R1', 'PRKACG',
# 'EEF2K','PPP3R2', 'RGS2', 'NPPA', 'CACNA1S','PRKACB', 'PRKACA', 'KCNJ5','RHOA', 'KCNJ6',
# 'PPP1R12A', 'PPP1R12B', 'JUN', 'KCNJ12', 'KCNJ9', 'KCNJ14', 'NFATC4', 'NFATC3', 'NFATC2', 'NFATC1',
# 'GNAO1', 'CAMK4', 'CAMK1', 'PPP1R12C', 'NPR1', 'NPR2', 'PIK3R5', 'ITPR2', 'ITPR3', 'OXT',
# 'ITPR1', 'PIK3R6',  'PPP3CA', 'PPP3CB', 'PPP3CC', 'CD38', 'CAMK1D', 'MEF2C', 'NOS3', 'FOS',
# 'PLCB4', 'JMJD7-PLA2G4B', 'KRAS', 'PLCB2', 'CAMK1G', 'PLCB3', 'PLCB1', 'MYLK2', 'RYR2', 'RYR3',
# 'CAMK2D', 'MYLK3', 'SRC', 'RYR1', 'CDKN1A', 'CAMK2A', 'CAMK2B', 'PRKAG2', 'PRKAG3', 'PRKAG1',
# 'GNAI1', 'GNAI2', 'CAMKK2', 'MYLK4', 'PTGS2', 'GNAI3', 'PIK3CG', 'CACNG7', 'CACNG8', 'MAPK3',
# 'CACNG1', 'MAPK1', 'HRAS', 'CACNG2', 'CACNG3', 'MAPK7', 'CAMK2G', 'CACNG4', 'KCNJ2', 'KCNJ3',
# 'CACNG5', 'CACNG6', 'KCNJ4')


dnds_primates_OT <- fread(paste0(BASE, "genevo_2021-04-28.tsv"))
#View(dnds_primates_OT)

ids_OT <- data.frame(dnds_primates_OT$`Entrez ID`)

# generally, most of the genes from the OT pathway geneset in HUMANS compared to the common primate ancestor have 
# a dN/dS ratio < 1, indicating evolutionary constraint and high conservation.
# For direct comparison against the neanderthals, refer to NSS score. 


### ----------------- Annotated box plots with phylo tree

# preparation

dnds_primates_OT$Gene <- as.factor(dnds_primates_OT$Gene)
head(dnds_primates_OT)

## functions for whisker length adjustment

o <- function(x) {
  subset(x, x == max(x) | x == min(x))
}

f <- function(x) {
  r <- quantile(x, probs = c(0.00, 0.25, 0.5, 0.75, 1))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

## phylogenetic tree generation

# create phylogenetic template tree
# template/orientation, generated with https://www.megasoftware.net/: 1. download software, 2. create custom tree with option "user tree"
tree_t <- fread("E:/Other_data/phylo_tree_primates", header = F)
View(tree_t)

# generate tree according to the template
text.string<-
  "(C. jacchus,(M. mulatta,(P. abelii,(G. gorilla,(P. troglodytes,(H. denisova,(H. neanderthalensis,H. sapiens)))))));"
treee<-read.tree(text=text.string)
ape::write.nexus(treee, file=paste0(BASE, "primate_pt.nex"))   # save as .nex file

# adjust x axis space to later fit the horizontal barplot
gg_tr <- ggtree(treee) + geom_tiplab(align=TRUE) +
  scale_x_continuous(expand=expansion(1)) +
  xlab("") +
  theme(axis.title.x=element_text(margin = margin(t = 40, r = 0, b = 0, l = 0)))
gg_tr



# plotting

# high quality
subset_hq <- dnds_primates_OT[, c(2, 6, 9, 12, 15, 18, 21, 24, 27)]

colnames(subset_hq) <- c("Gene",
                         "H. sapiens", 
                         "H. neanderthalensis", 
                         "H. denisova", 
                         "P. troglodytes", 
                         "G. gorilla", 
                         "P. abelii", 
                         "M. mulatta", 
                         "C. jacchus")

subset_hq <- subset_hq %>% pivot_longer(c("H. sapiens", 
                                          "H. neanderthalensis", 
                                          "H. denisova", 
                                          "P. troglodytes", 
                                          "G. gorilla",
                                          "P. abelii",
                                          "M. mulatta",
                                          "C. jacchus"),
                                        names_to = "Species", values_to = "value")


subset_hq$Species <- factor(subset_hq$Species , levels = c("H. sapiens", 
                                                           "H. neanderthalensis", 
                                                           "H. denisova", 
                                                           "P. troglodytes", 
                                                           "G. gorilla",
                                                           "P. abelii",
                                                           "M. mulatta",
                                                           "C. jacchus"))

subset_hq$Gene <- as.factor(subset_hq$Gene)

p_hq <- ggplot(subset_hq, aes(x = value, y = Species, fill = Species)) + theme_bw()
p_hq <- p_hq +  
  stat_summary(fun.data=f, geom="boxplot", alpha=0.5, show.legend = FALSE, width=.75) +
  stat_summary(fun = o, geom="point") 
p_hq <- p_hq + scale_y_discrete(limits = rev(levels(subset_hq$Species)))
p_hq <- p_hq + geom_point(aes(fill=Species), size = 4, colour="black", shape = 21, position = position_jitterdodge()) 
p_hq <- p_hq + xlab("dN/dS ratio") 
p_hq <- p_hq + theme(axis.title.x = element_text(size=20, face="bold", margin = margin(t = 10, r = 0, b = 0, l = 0)),
                     axis.text.x  = element_text(size = 15),
                     axis.ticks.y = element_blank(),       
                     axis.text.y  = element_blank(),         
                     axis.title.y = element_blank(),
                     panel.border = element_blank()) 
p_hq <- p_hq + viridis::scale_fill_viridis(option = 'viridis', discrete = T)
p_hq <- p_hq + theme(legend.position = "none")

p_hq

ggsave(filename = paste0(BASE, "dnds_OTgeneset_hq.pdf"), p_hq,
       width = 15, height = 8, units = "in", device='pdf')

# combine high quality barplot and phylogenetic tree
dnds_OT_tree_hq <- grid.arrange(gg_tr, p_hq, layout_matrix = rbind(c(1, 1, 2, 2, 2, 2, 2, 2, 2),
                                                                   c(1, 1, 2, 2, 2, 2, 2, 2, 2)))

# save plot
ggsave(filename = paste0(BASE, "dndsOT_tree_hq.pdf"), dnds_OT_tree_hq,
       width = 20, height = 8, units = "in", device='pdf')


# medium quality
subset_mq <- dnds_primates_OT[, c(2, 7, 10, 13, 16, 19, 22, 25, 28)]

colnames(subset_mq) <- c("Gene",
                         "H. sapiens", 
                         "H. neanderthalensis", 
                         "H. denisova", 
                         "P. troglodytes", 
                         "G. gorilla", 
                         "P. abelii", 
                         "M. mulatta", 
                         "C. jacchus")

subset_mq <- subset_mq %>% pivot_longer(c("H. sapiens", 
                                          "H. neanderthalensis", 
                                          "H. denisova", 
                                          "P. troglodytes", 
                                          "G. gorilla",
                                          "P. abelii",
                                          "M. mulatta",
                                          "C. jacchus"),
                                        names_to = "Species", values_to = "value")


subset_mq$Species <- factor(subset_mq$Species , levels = c("H. sapiens", 
                                                           "H. neanderthalensis", 
                                                           "H. denisova", 
                                                           "P. troglodytes", 
                                                           "G. gorilla",
                                                           "P. abelii",
                                                           "M. mulatta",
                                                           "C. jacchus"))

subset_mq$Gene <- as.factor(subset_mq$Gene)

p_mq <- ggplot(subset_mq, aes(x = value, y = Species, fill = Species)) + theme_bw()
p_mq <- p_mq +  
  stat_summary(fun.data=f, geom = "boxplot", alpha = 0.5, show.legend = FALSE, width=.75) +
  stat_summary(fun = o, geom = "point") 
p_mq <- p_mq + scale_y_discrete(limits = rev(levels(subset_mq$Species)))
p_mq <- p_mq + geom_point(aes(fill = Species), size = 4, colour = "black", shape = 21, position = position_jitterdodge()) 
p_mq <- p_mq + xlab("dN/dS ratio") 
p_mq <- p_mq + theme(axis.title.x = element_text(size=20, face = "bold", margin = margin(t = 10, r = 0, b = 0, l = 0)),
                     axis.text.x  = element_text(size = 15),
                     axis.ticks.y = element_blank(),       
                     axis.text.y  = element_blank(),         
                     axis.title.y = element_blank(),
                     panel.border = element_blank()) 
p_mq <- p_mq + viridis::scale_fill_viridis(option = 'plasma', discrete = T)
p_mq <- p_mq + theme(legend.position = "none")

p_mq

ggsave(filename = paste0(BASE, "dnds_OTgeneset_mq.pdf"), p_mq,
       width = 15, height = 8, units = "in", device='pdf')

# combine medium quality barplot and phylogenetic tree
dnds_OT_tree_mq <- grid.arrange(gg_tr, p_mq, layout_matrix = rbind(c(1, 1, 2, 2, 2, 2, 2, 2, 2),
                                                                   c(1, 1, 2, 2, 2, 2, 2, 2, 2))) 

# save plot
ggsave(filename = paste0(BASE, "dndsOT_tree_mq.pdf"), dnds_OT_tree_mq,
       width = 20, height = 8, units = "in", device='pdf')


# low quality
subset_lq <- dnds_primates_OT[, c(2, 8, 11, 14, 17, 20, 23, 26, 29)]

colnames(subset_lq) <- c("Gene",
                         "H. sapiens", 
                         "H. neanderthalensis", 
                         "H. denisova", 
                         "P. troglodytes", 
                         "G. gorilla", 
                         "P. abelii", 
                         "M. mulatta", 
                         "C. jacchus")

subset_lq <- subset_lq %>% pivot_longer(c("H. sapiens", 
                                          "H. neanderthalensis", 
                                          "H. denisova", 
                                          "P. troglodytes", 
                                          "G. gorilla",
                                          "P. abelii",
                                          "M. mulatta",
                                          "C. jacchus"),
                                        names_to = "Species", values_to = "value")


subset_lq$Species <- factor(subset_lq$Species , levels = c("H. sapiens", 
                                                           "H. neanderthalensis", 
                                                           "H. denisova", 
                                                           "P. troglodytes", 
                                                           "G. gorilla",
                                                           "P. abelii",
                                                           "M. mulatta",
                                                           "C. jacchus"))

subset_lq$Gene <- as.factor(subset_lq$Gene)

p_lq <- ggplot(subset_lq, aes(x = value, y = Species, fill = Species)) + theme_bw()
p_lq <- p_lq +  
  stat_summary(fun.data=f, geom="boxplot", alpha=0.5, show.legend = FALSE, width=.75) +
  stat_summary(fun = o, geom="point") 
p_lq <- p_lq + scale_y_discrete(limits = rev(levels(subset_lq$Species)))
p_lq <- p_lq + geom_point(aes(fill=Species), size = 4, colour="Black", shape = 21, position = position_jitterdodge()) 
p_lq <- p_lq  + xlab("dN/dS ratio") 
p_lq <- p_lq + theme(axis.title.x = element_text(size=20, face="bold", margin = margin(t = 10, r = 0, b = 0, l = 0)),
                     axis.text.x  = element_text(size = 15),
                     axis.ticks.y = element_blank(),       
                     axis.text.y  = element_blank(),         
                     axis.title.y = element_blank(),
                     panel.border = element_blank()) 
p_lq <- p_lq + viridis::scale_fill_viridis(option = 'cividis', discrete = T)
p_lq <- p_lq + theme(legend.position = "none")

p_lq

ggsave(filename = paste0(BASE, "dnds_OTgeneset_lq.pdf"), p_lq,
       width = 15, height = 8, units = "in", device='pdf')


# combine low quality barplot and phylogenetic tree
dnds_OT_tree_lq <- grid.arrange(gg_tr, p_lq, layout_matrix = rbind(c(1, 1, 2, 2, 2, 2, 2, 2, 2),
                                                                   c(1, 1, 2, 2, 2, 2, 2, 2, 2)))

# save plot
ggsave(filename = paste0(BASE, "dndsOT_tree_lq.pdf"), dnds_OT_tree_lq,
       width = 20, height = 8, units = "in", device='pdf')


####################
# end of script
####################








